### PR TITLE
Write tests

### PR DESCRIPTION
**Pull request by davidlatwe**
Thought Allzpark could use some test cases for developing new features or implementing fixes, but honestly I don't have any experiences on writing test for GUI (this is my first time), also not sure about what should we test against to.

But I think we should have tests anyway, so maybe we could start from this draft ?

Any inputs are welcome. :)

### CODE REVIEW

**Comment by davidlatwe** [comment]
Oh, be ware that your Allzpark preference will be cleaned when running test.

**Comment by mottosso** [comment]
Good initiative. :) Happy for you to take the lead and determine whether and when this is ready to merge.

**Comment by davidlatwe** [comment]
So I was trying to run tests in Azure pipielines, and bumped into a few problems. Leaving notes here.

Ubuntu 16.04 can install pyside with `apt-get install python-pyside`, but no pyside2 available. Ubuntu 20.04 can install pyside2, but no pyside. Using `Xvfb` + pyside2 passed the test, seems doesn't works with pyside (tests still runnning after an hour). Qt5 has an environment var `QT_QPA_PLATFORM`, [set to `"offscreen"`](https://stackoverflow.com/a/55442821) seems can be an alternative of `Xvfb`.

Building PySide on MacOS takes long long time.

Windows Python 2.7 somehow passed all the tests but still error out at the end (powershell [return code `1`](https://dev.azure.com/davidlatwe/allzpark/_build/results?buildId=40&view=logs&j=caf69a0e-a9ee-58f6-961d-97e6c7b37663&t=5facfa1c-6ea0-5391-2a16-7cfade46a796&l=62), cmd exited with [code `-1073741819`](https://dev.azure.com/davidlatwe/allzpark/_build/results?buildId=55&view=logs&j=caf69a0e-a9ee-58f6-961d-97e6c7b37663&t=59757ea5-1804-5497-0cdf-5a6aac232c9c&l=64)).

`bleeding-rez` doesn't handled memory-based package repository's address properly, should be an easy fix (see [log](https://dev.azure.com/davidlatwe/allzpark/_build/results?buildId=55&view=logs&j=dafe87f1-ac06-52af-bb6a-b9c8a6e21a2e&t=c439253b-0432-50e0-1966-c5493a5f4b75&l=191)).

Although `time.clock` has been deprecated but not yet removed before Python 3.7 accroding to [doc](https://docs.python.org/3/whatsnew/3.8.html#api-and-feature-removals), but the Python 3.7 in Azure pipelines' Unbuntu [doesn't have that attribute](https://dev.azure.com/davidlatwe/allzpark/_build/results?buildId=53&view=logs&j=826ba1ed-089c-5d2a-1529-2c33ca80ec01&t=45032c61-2362-52d5-c08d-e291b2212141&l=290). (fixed in 99c7de7)

Vandorized `transitions` module isn't using vendorized `six` (see [log](https://dev.azure.com/davidlatwe/allzpark/_build/results?buildId=34&view=logs&j=244fe771-0d59-5369-7134-684ebd982ec4&t=9cde3e8a-23e6-550c-f854-9bb8677b5c74&l=47)). (fixed in ec45019)

Here's my [ci history](https://dev.azure.com/davidlatwe/allzpark/_build?definitionId=2&_a=summary) of all the testing commits. 😓

**Comment by davidlatwe** [comment]
Setting this PR as "ready to review" for running tests.

**Comment by mottosso** [comment]
> Ubuntu 16.04 can install pyside with apt-get install python-pyside, but no pyside2 available. Ubuntu 20.04 can install pyside2, but no pyside

Sorry I meant to reply to this sooner! Yes, haha. I know exactly what you mean. The Qt.py project struggles with this too.

I see you just dropped 2.7 support in testing, I think that's the way to go. There's no need  to test this with every version of Python and Qt binding. Keep it simple; some tests in some form are better than none in any form.

**Comment by davidlatwe** [comment]
> Keep it simple; some tests in some form are better than none in any form.

Totally !
One last thing I am trying to solve is this: ["....QThread: Destroyed while thread is still running"](https://mottosso.visualstudio.com/allzpark/_build/results?buildId=916&view=logs&j=beb709dc-c613-521e-3caa-ee6dea8649da&t=3db5e6a2-1e57-5c95-4f0f-c2d277866c24&l=35), this error pops up randomly, but shouldn't hard to solve.

**Comment by mottosso** [comment]
Is it an error though? I suspect it's showing up just as Python is about to shutdown; from another error.

**Comment by davidlatwe** [comment]
> I suspect it's showing up just as Python is about to shutdown; from another error.

Not sure.., but I see there are 4 dots before the line "QThread: Destroyed while thread is still running", and there are 5 tests, which means previous 4 all passed but the last one. So I guess it's because the fast exiting. 🤔

**Comment by mottosso** [comment]
There's a verbose mode to tests (if it's using nose?) (which I really think should be default, but alas) to turn those dots into lines, with the name of each test on it an a FAIL or OK. That could help.

**Comment by davidlatwe** [comment]
Yap.. should have more info :(
For future good, let's use `nose` !

**Comment by davidlatwe** [comment]
Hooray ! Refactored and `nose` adopted, all tests passed !
I think we are ready to merge this !

**Comment by mottosso** [comment]
Woho! Nice work :)

**Comment by davidlatwe** [comment]
Merging this !

**Pull request merged**
