### PR TITLE
Replace header profile widgets with profiles dock page

### PR DESCRIPTION
**Pull request by davidlatwe**
### Proposal

Instead of using line-edit widget, change to use treeview to view/select/activate profiles.

Here's the result :

image

And a close look on the profile tool bar :

image

### Features

* You can set/unset favorite profile by the `star` button.
* Profiles that are not set as favorite, will be hidden/shown when toggling `filter` button.
* You can search all profiles by the text search bar, profiles that were hidden by the `filter` button will still match and present.
* Profile version picking is an advanced feature, so it is disabled by default, but can be enabled by toggling the `version` button.
* Right click on the profile item in treeview to show menu and activate profile from there.
* The icon color of current active profile item is green, others are brown.
* Current profile will not be filter out even it's not set as favorite.
* Profiles can be categorized by the package attribute `_data["category"]`. The default category name is `"profiles"` as shown in above image if that attribute is not presented.

### CODE REVIEW

**Comment by mottosso** [comment]
Like I've said in the chat, this is excellent work, thanks for this @davidlatwe!

What do we think about the space left behind where the old profile widget was? Maybe we could now shift all icons to the left, and close that gap?

image

**Comment by mottosso** [comment]
Alternatively, leave the profile image where it was to the left, and keep an empty space between it and the icons, like how it looks to the right?

image

**Comment by davidlatwe** [comment]
Oh yes, about the layout of those dock page toggle buttons on the header after this change, here's what I think :

I was actually thinking that we could change them into like the style I found in PyCharm :

image

Which is simple tiny icon + label style, and that will be less screen space used, and user would be a bit more clearer about what is that button/page is for with the label. (Allzpark logo will also be tinified and remain on the right side I guess)

But that's the future plan in my mind. What do you think ?

For now, I think I would go option 1), which is push all of them to the left side. :P
Because the dock toggle button were created in a for loop, and adding custom gap like the way they were (option 2)) would be adding a bit more code changes I think.

**Comment by mottosso** [comment]
> Which is simple tiny icon + label style, and that will be less screen space used, and user would be a bit more clearer about what is that button/page is for with the label. (Allzpark logo will also be tinified and remain on the right side I guess)

Hmmmmmmmmm :D I suppose it's subjective, but I find that visual more noisy, even though it takes up less space. I find that buttons invite curiosity and once you've found the buttons you're looking for you are unlikely to have to read its name again.

But, subjective, so I can appreciate that some may prefer the PyCharm style. I would make it an (non-default) option. Like the "Use small taskbar icons" in Windows or Unreal Engine.

> For now, I think I would go option 1), which is push all of them to the left side. :P

If possible, I think it would be most visually clear to move only the profile to the left, and keep the docking buttons in the centre like the original design. It gives them a distinct visual difference. Having them bunched together implies they perform a similar action.

**Comment by davidlatwe** [comment]
> But, subjective, so I can appreciate that some may prefer the PyCharm style. I would make it an (non-default) option. Like the "Use small taskbar icons" in Windows or Unreal Engine.

Good idea 👍🏼 

> Having them bunched together implies they perform a similar action.

Yeah that's true. See if I can pull this off today. 💪🏼

**Comment by davidlatwe** [comment]
Done, and I also made profile page to be dock at the left side by default, and will remain visible even when "allow multiple docks" is not enabled. This is expected, right ?

4869d3f7-5b87-4f29-a31e-498ad95c3bc6

**Comment by mottosso** [comment]
Oh! Hmmmmm, I see how it works now. That profile button is actually just another dock button, like the others. :D I dunno man, I might take back what I said about having it be separate from the other buttons, it does exactly the same thing. Hmmmm. What do you think? What feels right?

I kind of like it to the left, because it is special in that it will show the project icon, and it is probably more used then the others.

> and will remain visible even when "allow multiple docks" is not enabled. This is expected, right ?

Good question. I'll trust your judgement on this.

**Comment by davidlatwe** [comment]
> What do you think? What feels right?
> I kind of like it to the left, because it is special in that it will show the project icon, and it is probably more used then the others.

Yeah, it is a special one indeed, so I like it solely on the left side as well. :P

Previously I prefer to push those dock toggle buttons to the left side all together was simply because easier to implement, but turns out it wasn't that hard (fe4dc92).

Now I think the functionality is good to go, but I'd like to polish the icons, and once I done that I think we could bump the version up to `1.3.0` and make a release ?

**Comment by mottosso** [comment]
> Now I think the functionality is good to go, but I'd like to polish the icons, and once I done that I think we could bump the version up to 1.3.0 and make a release ?

Sounds good to me. Thanks @davidlatwe

**Pull request merged**
