### PR TITLE
Fix missing collect .svg icons in setup.py

### LINKED ISSUE #114: Missing collect .svg icons in setup.py
Hi,

when I via command line `rez env pipz -- install allzpark` to install, I found that some SVG icons are missing in the profile widget.
 
image

### PR DESCRIPTION
**Pull request by loonghao**
Hi @mottosso this PR is fix #114 please have a look, Thanks.
image
after change
image

### CODE REVIEW

**Comment by mottosso** [comment]
Oh! Haha, that's what I get for reading and responding to my mailbox one email at a time. :) (Having just suggested this in #114)

Thanks @loonghao this looks just right!

**Comment by loonghao** [comment]
@mottosso Could you please help create a new tag for this update? due to I don't have permission to do that, Thanks.

**Comment by mottosso** [comment]
One minute, I made a mistake xD

**Comment by mottosso** [comment]
Ok, it's done. :)

**Pull request merged**
