### PR TITLE
Opt-out vendor six

### LINKED ISSUE #137: register vendered six into global namespace may break stuff
**This is an edge case I suppose**, strange `ModuleNotFoundError` raise when something requires `six.moves`.

In my case it was a [python rez-package](https://github.com/davidlatwe/rez-python-venv) that uses `pythonfinder` module to list out system python and provide venv to use. And the `pythonfinder` module has [it's own `six.moves` registered](https://github.com/sarugaku/pythonfinder/blob/dfac150ffeaccbcb3c2867c5429b38b568d85a8d/src/pythonfinder/utils.py#L21-L29) and the `ModuleNotFoundError` raised from there due to the module `six` is already imported as global one in Allzpark launch-time and it doesn't have `.moves`.

https://github.com/mottosso/allzpark/blob/43eb8e0d8d89449ab1accae9653687fc51dc37a6/allzpark/cli.py#L192-L198

**Although following log message is not generated from the current master branch of Allzpark but my forked one, but the root cause is the same.**

<details>
<summary>Full error log</summary>

```
$ rez-park
==============================
 allzpark (2.0.48)
==============================
- Loading Rez.. (2.88.1-m) - ok 0.00
- Loading Qt.. (PySide2 - 5.15.2) - ok 0.88
- Loading allzpark.. (2.0.48) - ok 0.10
- Loading allzparkconfig.. ok - 0.00
- Loading application parent environment.. ok - 0.00
- Loading preferences.. (C:/Users/davidlatwe.lai/AppData/Roaming/Allzpark/preferences.ini) ok - 0.01
------------------------------
- Loading themes.. ok - 0.02
- Loading environment plugin.. no plugin - ok
- Resolved contexts.. ok 0.11s
Traceback (most recent call last):
  File "c:\users\davidlatwe.lai\pipeline\allzpark\allzpark\control.py", line 970, in on_apps_not_found
    raise error
  File "c:\users\davidlatwe.lai\pipeline\allzpark\allzpark\util.py", line 165, in run
    result = self.target(*self.args, **self.kwargs)
  File "c:\users\davidlatwe.lai\pipeline\allzpark\allzpark\control.py", line 1240, in _list_apps
    for tool_alias, tool_entry in suite.get_tools().items():
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\suite.py", line 307, in get_tools
    self._update_tools()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\suite.py", line 717, in _update_tools
    context = self.context(context_name)
  File "c:\users\davidlatwe.lai\pipeline\sweet\src\sweet\_rezapi.py", line 50, in context
    context = ResolvedContext(self._requests[name])
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\resolved_context.py", line 308, in __init__
    resolver.solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\memcached.py", line 267, in wrapper
    return func(*nargs, **kwargs)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\resolver.py", line 119, in solve
    solver = self._solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\resolver.py", line 404, in _solve
    solver.solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 2082, in solve
    self.solve_step()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 2162, in solve_step
    new_phase = phase.solve()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 1368, in solve
    scope = _PackageScope(req, solver=self.solver)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 972, in __init__
    package_request.name, package_request.range)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 2338, in _get_variant_slice
    package_name=package_name, range_=range_)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 941, in get_variant_slice
    variant_list = _PackageVariantList(package_name, self.solver)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\solver.py", line 470, in __init__
    paths=self.solver.package_paths):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\packages.py", line 558, in iter_packages
    for package_resource in repo.iter_packages(family_resource):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\memcached.py", line 262, in wrapper
    for result in func(*nargs, **kwargs):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 560, in iter_packages
    for package in self.get_packages(package_family_resource):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\backport\lru_cache.py", line 74, in wrapper
    result = user_function(*args, **kwds)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 1130, in _get_packages
    return [x for x in package_family_resource.iter_packages()]
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 1130, in <listcomp>
    return [x for x in package_family_resource.iter_packages()]
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 313, in iter_packages
    if config.allow_unversioned_packages and not self.versions:
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\data_utils.py", line 245, in __get__
    result = self.func(instance)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\data_utils.py", line 657, in getter
    if key not in (self._data or {}):
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\data_utils.py", line 245, in __get__
    result = self.func(instance)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\resources.py", line 97, in _data
    data = self._load()
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rezplugins\package_repository\filesystem.py", line 337, in _load
    disable_memcache=self._repository.disable_memcache
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 141, in load_from_file
    update_data_callback=update_data_callback)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\utils\memcached.py", line 383, in wrapper
    result = func(*nargs, **kwargs)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 160, in _load_from_file
    return _load_file(filepath, format_, update_data_callback)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 174, in _load_file
    result = load_func(f, filepath=filepath)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 231, in load_py
    return _load_py(stream, filepath=filepath)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 269, in _load_py
    result = process_python_objects(result, filepath=filepath)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 393, in process_python_objects
    data = _process(data)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 311, in _process
    value[k] = _process(v)
  File "c:\users\davidlatwe.lai\pipeline\rez\src\rez\serialise.py", line 345, in _process
    value_ = fn()
  File "c:\users\davidlatwe.lai\rez\packages\combined\python.py", line 11, in versions
    from pythonfinder import Finder
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\pythonfinder\__init__.py", line 10, in <module>
    from .models import SystemPath, WindowsFinder
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\pythonfinder\models\__init__.py", line 11, in <module>
    from ..utils import KNOWN_EXTS, unnest
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\pythonfinder\utils.py", line 28, in <module>
    from six.moves import Iterable  # type: ignore  # noqa  # isort:skip
  File "C:\Users\davidlatwe.lai\.rezup\.main\revisions\1621512586.536713\venv\rez\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'six.moves'
```

</details>

I will resolve this on my fork for now, by removing `six` from vendor because the branch I am working on is not supporting Python 2 and like I said above, this should be an edge case. Just reporting here for the record.

### PR DESCRIPTION
**Pull request by davidlatwe**
This close #137 , see the issue for detail.

### CODE REVIEW

**Comment by mottosso** [comment]
Any idea what might be up with that test? :O

**Comment by davidlatwe** [comment]
No sure,.. but I am sure that isn't related to this change and all tests passing on my Windows machine.
Maybe subprocess cannot work properly in there ?

**Comment by davidlatwe** [comment]
By re-run that failed job a few more times, I found there are actually two tests may fail on Windows server.
Will push another PR later with minor changes on README to see if current master still passing.

**Comment by mottosso** [comment]
This probably won't solve the CI issue, but there is an alternative way we can solve the original issue that might be better?

```py
from allzpark.vendor import six
sys.modules["six"] = six

# import everything using global six
import bleeding_rez.some_sub_package
import that_other_package
import etc

# Restore order
sys.modules.pop("six")
```

With that, we could keep vendoring six without risking any leakage to other packages. Finding which packages to import should be a matter of finding those that call `^import six`, the `^` being a regular expression for "start of line" (unless it was `$`? I always confuse the two..)

Thoughts? :O

**Comment by davidlatwe** [comment]
Hmmm ~
Not sure I understand, where does that code snippet get run ?

And, yep, it is `^` for start and `$` for ending. :)

**Comment by mottosso** [comment]
It'd happen right here:

https://github.com/mottosso/allzpark/blob/43eb8e0d8d89449ab1accae9653687fc51dc37a6/allzpark/cli.py#L197

**Comment by davidlatwe** [comment]
Hey @mottosso , sorry for delay :P

Tested above code snippet, and it still won't work unless you also importing `allzpark.vendor.six.moves` before importing everything else.

How about this ?

```python
# cli.py L180
with timings("- Loading Qt.. ") as msg:
    ...
    from .vendor import six
    from .vendor.six import moves as six_moves

sys.modules["six"] = six
sys.modules["six.moves"] = six_moves
```

Just import `six.moves` from vendored `six` as well, this also fix my problem without removing `six` from vendor. With this, we shouldn't need to worry about other packages.

And to be more compatible, maybe this ?

```python
# cli.py L180
with timings("- Loading Qt.. ") as msg:
    ...
    try:
        import six
        from six import move as six_moves
    except ImportError:
        from .vendor import six
        from .vendor.six import moves as six_moves

sys.modules["six"] = six
sys.modules["six.moves"] = six_moves
```

**Comment by mottosso** [comment]
> Tested above code snippet, and it still won't work

Hmm, that doesn't make sense. What did you import exactly? Once `six` has been imported by all of our vendored libraries and removed from `sys.modules` it should have no effect on anyone else `import six`.

> sys.modules["six.moves"] = six_moves

This would be dangerous, as we now can't be sure what version of six we've actually got here. Each submodule could come from a different version. Would be very challenging to debug.

```py
print(six.__version__)  # Is this true?
```

**Comment by davidlatwe** [comment]
> Once `six` has been imported by all of our vendored libraries and removed from `sys.modules` it should have no effect on anyone else import `six`.

Ah, I missed interpreted what the comment "import everything using global six" means. Then that should work, but..

But all Allzpark vendored libraries are using relative import currently :)

**Comment by davidlatwe** [comment]
From search result, only `vendor/transitions` is using `six` and the import statement is relative.

**Comment by mottosso** [comment]
:O Then I have been confused this whole time. Sorry! In that case, I can't see any other option than the remove it six vendor. Happy for you to merge this when you're happy!

**Comment by mottosso** [comment]
Yes, if nothing in vendor uses six globally, then I'm not sure why this got added in the first place. :S If it works without it, then all should be well.

**Comment by davidlatwe** [comment]
Looks like the CI failing may be related to the version bump of Windows image. Merging this for now, will deal the CI test later.

**Pull request merged**
